name: pyb
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2020.6.20=pyhd3eb1b0_3
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.2=py36h06a4308_0
  - python=3.6.13=h12debd9_1
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py36h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - build==0.7.0
    - charset-normalizer==2.0.10
    - ci-info==0.2.0
    - click==8.0.3
    - decorator==4.4.2
    - etelemetry==0.2.2
    - filelock==3.4.1
    - idna==3.3
    - importlib-metadata==4.8.3
    - isodate==0.6.1
    - lxml==4.7.1
    - networkx==2.5.1
    - nibabel==3.2.1
    - nipype==1.7.0
    - numpy==1.19.5
    - packaging==21.3
    - pep517==0.12.0
    - prov==2.0.0
    - pydot==1.4.2
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - rdflib==5.0.0
    - requests==2.27.1
    - scipy==1.5.4
    - simplejson==3.17.6
    - six==1.16.0
    - tomli==1.2.3
    - traits==6.3.2
    - typing-extensions==4.0.1
    - urllib3==1.26.7
    - zipp==3.6.0
